version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
      - mongo
      - neo4j

#  frontend:
#    build: ./frontend
#   container_name: react-frontend
#   ports:
#     - "3000:3000"
#   volumes:
#     - ./frontend:/app
#   stdin_open: true
#   tty: true

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: iocuser
      POSTGRES_PASSWORD: iocpass
      POSTGRES_DB: threatdb

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  neo4j:
    image: neo4j:5.14
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test12345
    volumes:
      - ./neo4j-data:/data
